CREATE TYPE PROJECT_CATEGORY AS ENUM ('GENERAL', 'STAGE');
CREATE TYPE PROJECT_ATTRIBUTE AS ENUM ('ACADEMIC', 'ARTISTIC', 'COMMITTEE');

CREATE TABLE projects (
    id SMALLSERIAL PRIMARY KEY,
    owner_id UUID REFERENCES users UNIQUE NOT NULL,
    sub_owner_id UUID REFERENCES users,
    name VARCHAR(100) NOT NULL,
    kana_name VARCHAR(100) NOT NULL,
    group_name VARCHAR(100) NOT NULL,
    kana_group_name VARCHAR(100) NOT NULL,
    description VARCHAR(500) NOT NULL,
    category PROJECT_CATEGORY NOT NULL,
    attributes PROJECT_ATTRIBUTE[] NOT NULL
);
