CREATE EXTENSION pgcrypto;

CREATE TYPE AFFILIATION_TYPE AS ENUM ('UNDERGRADUATE', 'GRADUATE', 'TEACHER');
CREATE TYPE USER_ROLE AS ENUM ('ADMIN', 'COMMITTEE', 'GENERAL');

CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(128) NOT NULL,
    kana_name VARCHAR(128) NOT NULL,
    email VARCHAR(254) UNIQUE NOT NULL,
    phone_number VARCHAR(11) NOT NULL,
    student_id VARCHAR(9) NOT NULL,
    affiliation_name VARCHAR(64),
    affiliation_type AFFILIATION_TYPE NOT NULL,
    role USER_ROLE NOT NULL,
    auth_id VARCHAR(64) NOT NULL
);