openapi: 3.0.0
info:
  title: sos
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
paths:
  /users:
    post:
      summary: Create user
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/user.v1.yaml
      operationId: post-users
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                kanaName:
                  type: string
                phoneNumber:
                  type: string
                studentId:
                  type: string
                affiliationName:
                  type: string
                affiliationType:
                  type: string
                '':
                  type: string
      security:
        - Authorization: []
      parameters: []
    get:
      summary: List users
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/user.v1.yaml
      operationId: get-users
      security:
        - Authorization: []
components:
  schemas: {}
  securitySchemes:
    Authorization:
      type: http
      scheme: Bearer
      description: Auth0 idToken
