name: Build and Release

on:
  push:
    tags:
      - "release/*"

env:
  GITHUB_SHA: ${{ github.sha }}
  IMAGE_NAME: sos20
  DOCKER_BUILDKIT: 1

jobs:
  build:
    name: Build and Push
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Login to Sakura Container Registry
        run: docker login sohosai.sakuracr.jp -u ${{ secrets.SAKURA_REG_USERNAME }} -p ${{ secrets.SAKURA_REG_PASSWORD }}

      - name: Build image
        run: docker build -t sohosai.sakuracr.jp/${IMAGE_NAME}:${GITHUB_SHA} --file Dockerfile .

      - name: Push image
        run: docker push sohosai.sakuracr.jp/${IMAGE_NAME}:${GITHUB_SHA}

  release:
    name: Release
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          repository: "sohosai/sos20-infra"
          ref: "master"
          token: ${{ secrets.GITHUB_PAT }}

      - name: "Setup Terraform Provider for SakuraCloud"
        run: |
          wget https://github.com/sacloud/terraform-provider-sakuracloud/releases/download/v2.2.0/terraform-provider-sakuracloud_2.2.0_linux-amd64.zip
          unzip terraform-provider-sakuracloud_2.2.0_linux-amd64.zip

      - name: "Terraform Init"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TF_VERSION }}
          tf_actions_cli_credentials_token: ${{ secrets.TF_TOKEN }}
          tf_actions_subcommand: "init"
          tf_actions_comment: false

      - name: "Terraform Taint"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TF_VERSION }}
          tf_actions_cli_credentials_token: ${{ secrets.TF_TOKEN }}
          tf_actions_subcommand: "taint"
          tf_actions_comment: false
          args: "sakuracloud_server.sos_server sakuracloud_disk.sos_disk"

      - name: "Terraform Plan"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TF_VERSION }}
          tf_actions_subcommand: "plan"
          tf_actions_comment: false

      - name: "Terraform Apply"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TF_VERSION }}
          tf_actions_subcommand: "apply"
          tf_actions_comment: false
    env:
      TF_VERSION: "latest"
      TF_VAR_SAKURA_TOKEN: ${{ secrets.SAKURA_TOKEN }}
      TF_VAR_SAKURA_SECRET: ${{ secrets.SAKURA_SECRET }}
      TF_VAR_SAKURA_REG_USERNAME: "actions"
      TF_VAR_SAKURA_REG_PASSWORD: ${{ secrets.SAKURA_REG_PASSWORD }}
      TF_VAR_DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      TF_VAR_PUBLIC_KEY: ${{ secrets.SERVER_PUBLIC_KEY }}
      TF_VAR_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
      TF_VAR_GIT_HASH: ${{ github.sha }}
